image: docker:latest

services:
  - name: docker:20-dind
    alias: docker
    command: [ "--tls=false" ]

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - build

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker build
        --tag $CONTAINER_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
        --tag $CONTAINER_IMAGE/$CI_COMMIT_REF_NAME:latest
        --build-arg deployment=$CI_COMMIT_REF_NAME .
    - docker push $CONTAINER_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE/$CI_COMMIT_REF_NAME:latest
